-- Top Spending Customer 
SELECT
blinkit_customers.customer_name, #Pkey: customer_id
SUM(blinkit_orders.order_total) AS total_spent #Fkey: customer_id
FROM blinkit_customers
INNER JOIN blinkit_orders
ON blinkit_customers.customer_id=blinkit_orders.customer_id
GROUP BY blinkit_customers.customer_name
ORDER BY total_spent DESC
LIMIT 10;

-- Total Revenue by Customer Segment
SELECT
blinkit_customers.customer_segment, #Pkey: customer_id
SUM(blinkit_orders.order_total) AS total_revenue #Fkey: customer_id
FROM blinkit_customers
INNER JOIN blinkit_orders
ON blinkit_customers.customer_id = blinkit_orders.customer_id
GROUP BY blinkit_customers.customer_segment
ORDER BY total_revenue DESC;

-- Most Sold Products
SELECT
blinkit_products.product_name, #Pkey: product_id
SUM(blinkit_order_items.quantity) AS total_quantity_sold #Fkey: product_id
FROM blinkit_products
INNER JOIN blinkit_order_items
ON blinkit_products.product_id = blinkit_order_items.product_id
GROUP BY blinkit_products.product_name
ORDER BY total_quantity_sold DESC
LIMIT 10;

-- Revenue Generated by Product Category
SELECT
blinkit_products.category, #Pkey: product_id
SUM(blinkit_order_items.quantity*blinkit_order_items.unit_price) AS revenue #Fkey: product_id
FROM blinkit_products
INNER JOIN blinkit_order_items
ON blinkit_products.product_id=blinkit_order_items.product_id
GROUP BY blinkit_products.category
ORDER BY revenue DESC;

-- Average Customer Rating by Delivery Status
SELECT
blinkit_delivery_performance.delivery_status, #Pkey: order_id
ROUND(AVG(blinkit_customer_feedback.rating),2) AS average_rating #Fkey: order_id
FROM blinkit_delivery_performance
INNER JOIN blinkit_customer_feedback
ON blinkit_delivery_performance.order_id=blinkit_customer_feedback.order_id
GROUP BY blinkit_delivery_performance.delivery_status;

-- Orders by State (Not working)
SELECT
blinkit_customers.area, #Pkey: customer_id
SUM(blinkit_orders.order_total) AS total_revenue #Fkey: customer_id
FROM blinkit_customers
INNER JOIN blinkit_orders
ON blinkit_customers.customer_id = blinkit_orders.customer_id
GROUP BY blinkit_customers.area
ORDER BY total_revenue DESC;

-- Average Order Value by Customer Segment
SELECT
blinkit_customers.customer_segment, #Pkey: customer_id
ROUND(AVG(blinkit_orders.order_total),2) AS average_order_value #Fkey: customer_id
FROM blinkit_customers
INNER JOIN blinkit_orders
ON blinkit_customers.customer_id = blinkit_orders.customer_id
GROUP BY blinkit_customers.customer_segment
ORDER BY average_order_value DESC;

-- Products Below Minimum Stock Level (Not working)
SELECT
blinkit_products.product_name, #Pkey: product_id
SUM(blinkit_inventory.damaged_stock) AS total_damaged_stock #Fkey: product_id
FROM blinkit_products
INNER JOIN blinkit_inventory
ON blinkit_products.product_id=blinkit_inventory.product_id
GROUP BY blinkit_products.product_name
ORDER BY total_damaged_stock DESC
LIMIT 10;

-- Customer Feedback by Segment
SELECT
blinkit_customers.customer_segment, #Pkey: customer_id 
ROUND(AVG(blinkit_customer_feedback.rating),2) AS average_rating #Fkey: customer_id 
FROM blinkit_customers
INNER JOIN blinkit_customer_feedback
ON blinkit_customers.customer_id = blinkit_customer_feedback.customer_id
GROUP BY blinkit_customers.customer_segment
ORDER BY average_rating DESC;

-- Revenue by Payment Method
SELECT
blinkit_orders.payment_method, 
ROUND(SUM(blinkit_orders.order_total),2) AS total_revenue
FROM blinkit_orders
GROUP BY blinkit_orders.payment_method
ORDER BY total_revenue DESC;
